
package vista;

import controlador.GestionFechas;
import controlador.Procedimientos;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import modelo.Hotel;

/**
 *
 * @author acebin
 */
public class Buscador extends javax.swing.JFrame {
    
    Hotel miHotel = new Hotel();
    Procedimientos miProcedimiento = new Procedimientos();
    
    //GestionFechas fechas = new GestionFechas();
    GestionFechas fechas = new GestionFechas();

    /**
     * Creates new form Buscador
     */
    public Buscador() {
        initComponents();
        fechas.limitarFecha(fechaEntrada, fechaSalida); //Limito las fechas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextBuscador = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        jLabelSeleccion = new javax.swing.JLabel();
        fechaEntrada = new com.toedter.calendar.JDateChooser();
        fechaSalida = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        wifi = new javax.swing.JRadioButton();
        piscina = new javax.swing.JRadioButton();
        spa = new javax.swing.JRadioButton();
        parking = new javax.swing.JRadioButton();
        aireA = new javax.swing.JRadioButton();
        restaurante = new javax.swing.JRadioButton();
        bar = new javax.swing.JRadioButton();
        gimnasio = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ubicación:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        getContentPane().add(jTextBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 210, 30));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 130, -1));

        jButton2.setText("Ver detalles");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 690, 150, -1));

        jLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jLista);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 230, 530));
        getContentPane().add(jLabelSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 680, 190, 60));
        getContentPane().add(fechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));
        getContentPane().add(fechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabel2.setText("Entrada");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setText("Salida");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel11.setText("Características:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 160, 40));

        wifi.setText("Wifi");
        getContentPane().add(wifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        piscina.setText("Piscina");
        getContentPane().add(piscina, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        spa.setText("Spa");
        getContentPane().add(spa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        parking.setText("Parking");
        getContentPane().add(parking, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        aireA.setText("Aire acondicionado");
        getContentPane().add(aireA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        restaurante.setText("Restaurante");
        getContentPane().add(restaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        bar.setText("Bar");
        getContentPane().add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        gimnasio.setText("Gimnasio");
        getContentPane().add(gimnasio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        
        DefaultListModel item = new DefaultListModel();
        
        try {
            //De esta manera asigno el nombre al hotel, y podré recuperarlo usando el metodo get
            miHotel.setNombre(this.jTextBuscador.getText());
            miProcedimiento.buscarHotel(miHotel.getNombre(), jLista, item);
        } catch (SQLException ex) {
            ex.getMessage();
        }
      
        
        
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaMouseClicked
        // TODO add your handling code here:
        //  
        this.miProcedimiento.asignarSeleccion( this.jLista, this.jLabelSeleccion);
        
    }//GEN-LAST:event_jListaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Pago miPago = new Pago();
        miPago.setVisible(true);
        dispose();
        //this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aireA;
    private javax.swing.JRadioButton bar;
    private com.toedter.calendar.JDateChooser fechaEntrada;
    private com.toedter.calendar.JDateChooser fechaSalida;
    private javax.swing.JRadioButton gimnasio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JToggleButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelSeleccion;
    private javax.swing.JList<String> jLista;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextBuscador;
    private javax.swing.JRadioButton parking;
    private javax.swing.JRadioButton piscina;
    private javax.swing.JRadioButton restaurante;
    private javax.swing.JRadioButton spa;
    private javax.swing.JRadioButton wifi;
    // End of variables declaration//GEN-END:variables
}
